title: CompSci Blogs
description: "August 2023 to June 2024"
owner_name: Nighthawk Coders
github_username: myamadriaga
baseurl: "/Mya2"
remote_theme: pages-themes/modernist@v0.2.0
plugins:
- jekyll-remote-theme
future: true
